### ISSUE TITLE
Add example for env variables needed for android build

### ISSUE THREAD

**Issue by stexa** [VoysAI/tflitec-rs#16]
I am not sure what is necessary to set for those environment variables:
  
      ANDROID_NDK_HOME
      ANDROID_NDK_API_LEVEL
      ANDROID_SDK_HOME
      ANDROID_API_LEVEL
      ANDROID_BUILD_TOOLS_VERSION

Do you have an example?

**Comment by ebraraktas** [comment]
`ANDROID_NDK_HOME` and `ANDROID_SDK_HOME` are just the paths of Android NDK and SDK respectively. See installation instructions for [NDK](https://developer.android.com/studio/projects/install-ndk)) and [SDK](https://developer.android.com/about/versions/14/setup-sdk). If you use `cargo ndk` (as suggested), it sets these environment variables automatically.

Other values must be selected considering your application build settings. You can use [the values in the official CI Dockerfile](https://github.com/tensorflow/tensorflow/blob/192763ed127381fc9ebbe207d1fb1ec1dd98e9a0/tensorflow/tools/ci_build/Dockerfile.android#L31-L35) if those work for you. In addition, you can see command line installation of the NDK and SDK [here](https://github.com/tensorflow/tensorflow/blob/192763ed127381fc9ebbe207d1fb1ec1dd98e9a0/tensorflow/tools/ci_build/Dockerfile.android#L37-L53).
